TEXTS = {
    "ru": {
        "choose_lang": "Выберите язык / Choose language / 选择语言",
        "agree_text": "Пожалуйста, подтвердите, что вы согласны с политикой и условиями.",
        "agree_btn": "Согласен",
        "main_title": "МЕНЮ ГЛАВНОЕ",
        "main_msg": "Добро пожаловать! Выберите раздел ⬇️",
        "about": "О сервисе и функциях",
        "login": "Войти в кабинет",
        "shorts": "Виральные shorts",
        "utils": "Полезные фишки",
        "support": "Служба поддержки",
        "pay_ton": "Оплатить в TON",
        "invite": "Пригласить друзей",
        "about_us": "О нас и сервисе",
        "later": "Позже",
        "back": "Назад",
        "invite_text": "Пригласите друзей: https://t.me/{bot}?start={uid}",
        # TON: просто сообщение, без адреса
        "pay_text": "Оплата в TON: скоро. Если нужно прямо сейчас — напишите в поддержку @fabricbotsupport.",
        "shorts_text": "Привет! Добавьте свои API ключи, чтобы регулярно получать лучшие видео.",
        "add_key": "Добавить ключ",
        "my_keys": "Мои ключи",
        "enter_key": "Отправьте ваш API ключ одним сообщением:",
        # Без бэкенда:
        "key_saved": "Ключ принят. На этой версии бот пока не подключает его автоматически.",
        "key_ok": "Готово! Подключение будет доступно после запуска сервиса.",
        "key_failed": "Не удалось обработать ключ. Попробуйте позже.",
        "no_keys": "Раздел «Мои ключи» появится после запуска сервиса.",
        "keys_header": "Ваши ключи:",
        "delete": "Удалить",
        "my_id_btn": "Мой Код",
        "my_id_text": "Ваш Код:\n<code>{id}</code>\n\nНажмите, чтобы скопировать.",
    },
    "en": {
        "choose_lang": "Choose language / Выберите язык / 选择语言",
        "agree_text": "Please confirm you agree to our policy and terms.",
        "agree_btn": "I agree",
        "main_title": "MAIN MENU",
        "main_msg": "Welcome! Pick a section ⬇️",
        "about": "About & Features",
        "login": "Sign in",
        "shorts": "Viral shorts",
        "utils": "Useful stuff",
        "support": "Support",
        "pay_ton": "Pay in TON",
        "invite": "Invite friends",
        "about_us": "About us & service",
        "later": "Later",
        "back": "Back",
        "invite_text": "Invite friends: https://t.me/{bot}?start={uid}",
        "pay_text": "TON payments: coming soon. If you need it now, please contact support @fabricbotsupport.",
        "shorts_text": "Hi! Add your API keys to receive top videos regularly.",
        "add_key": "Add key",
        "my_keys": "My keys",
        "enter_key": "Send your API key in a single message:",
        "key_saved": "Key received. In this version the bot doesn’t connect it yet.",
        "key_ok": "Done! Connection will be available once the service is live.",
        "key_failed": "Failed to process the key. Try later.",
        "no_keys": "“My keys” will be available once the service is live.",
        "keys_header": "Your keys:",
        "delete": "Delete",
        "my_id_btn": "My ID",
        "my_id_text": "Your chat ID:\n<code>{id}</code>\n\nTap to copy.",
    },
    "zh": {
        "choose_lang": "选择语言 / Choose language / Выберите язык",
        "agree_text": "请选择同意我们的政策和条款。",
        "agree_btn": "同意",
        "main_title": "主菜单",
        "main_msg": "欢迎！请选择 ⬇️",
        "about": "关于与功能",
        "login": "登录",
        "shorts": "爆款短视频",
        "utils": "实用功能",
        "support": "客服支持",
        "pay_ton": "用 TON 支付",
        "invite": "邀请好友",
        "about_us": "关于我们与服务",
        "later": "稍后",
        "back": "返回",
        "invite_text": "邀请好友：https://t.me/{bot}?start={uid}",
        "pay_text": "TON 支付：即将上线。如需现在开通，请联系客服 @fabricbotsupport。",
        "shorts_text": "你好！添加你的 API 密钥即可定期接收优质视频。",
        "add_key": "添加密钥",
        "my_keys": "我的密钥",
        "enter_key": "请一次性发送你的 API 密钥：",
        "key_saved": "已接收密钥。本版本暂不自动连接。",
        "key_ok": "完成！服务上线后将提供连接。",
        "key_failed": "处理密钥失败，请稍后再试。",
        "no_keys": "“我的密钥”将在服务上线后开放。",
        "keys_header": "你的密钥：",
        "delete": "删除",
        "my_id_btn": "我的 ID",
        "my_id_text": "你的 chat ID：\n<code>{id}</code>\n\n点击即可复制。",
    },
}
