TEXTS = {
    "ru": {
        "choose_lang": "Выберите язык / Choose language / 选择语言",
        "agree_text": "Пожалуйста, подтвердите, что вы согласны с политикой и условиями.",
        "agree_btn": "Согласен",
        "main_title": "МЕНЮ ГЛАВНОЕ",
        "main_msg": "Добро пожаловать! Выберите раздел ⬇️",
        "about": "О сервисе и функциях",
        "login": "Войти в кабинет",
        "shorts": "Виральные shorts",
        "utils": "Полезные фишки",
        "support": "Служба поддержки",
        "pay_ton": "Оплатить в TON",
        "invite": "Пригласить друзей",
        "about_us": "О нас и сервисе",
        "later": "Позже",
        "back": "Назад",
        "invite_text": "Пригласите друзей: https://t.me/{bot}?start={uid}",
        "pay_text": "Оплата в TON. Адрес: {addr}",
        "shorts_text": "Привет! Добавьте свои API ключи, чтобы регулярно получать лучшие видео.",
        "add_key": "Добавить ключ",
        "my_keys": "Мои ключи",
        "enter_key": "Отправьте ваш API ключ одним сообщением:",
        "key_saved": "Ключ отправлен. Проверяем подключение…",
        "key_ok": "Готово! Дальше работает наш сервис.",
        "key_failed": "Не удалось отправить ключ. Попробуйте позже.",
        "no_keys": "У вас пока нет ключей (или сервис недоступен).",
        "keys_header": "Ваши ключи:",
        "delete": "Удалить",
    },
    "en": {
        "choose_lang": "Choose language / Выберите язык / 选择语言",
        "agree_text": "Please confirm you agree to our policy and terms.",
        "agree_btn": "I agree",
        "main_title": "MAIN MENU",
        "main_msg": "Welcome! Pick a section ⬇️",
        "about": "About & Features",
        "login": "Sign in",
        "shorts": "Viral shorts",
        "utils": "Useful stuff",
        "support": "Support",
        "pay_ton": "Pay in TON",
        "invite": "Invite friends",
        "about_us": "About us & service",
        "later": "Later",
        "back": "Back",
        "invite_text": "Invite friends: https://t.me/{bot}?start={uid}",
        "pay_text": "Pay in TON. Address: {addr}",
        "shorts_text": "Hi! Add your API keys to receive top videos regularly.",
        "add_key": "Add key",
        "my_keys": "My keys",
        "enter_key": "Send your API key in a single message:",
        "key_saved": "Key sent. Checking…",
        "key_ok": "Done! The service will handle it next.",
        "key_failed": "Failed to send the key. Try later.",
        "no_keys": "No keys yet (or backend unavailable).",
        "keys_header": "Your keys:",
        "delete": "Delete",
    },
    "zh": {
        "choose_lang": "选择语言 / Choose language / Выберите язык",
        "agree_text": "请选择同意我们的政策和条款。",
        "agree_btn": "同意",
        "main_title": "主菜单",
        "main_msg": "欢迎！请选择 ⬇️",
        "about": "关于与功能",
        "login": "登录",
        "shorts": "爆款短视频",
        "utils": "实用功能",
        "support": "客服支持",
        "pay_ton": "用 TON 支付",
        "invite": "邀请好友",
        "about_us": "关于我们与服务",
        "later": "稍后",
        "back": "返回",
        "invite_text": "邀请好友：https://t.me/{bot}?start={uid}",
        "pay_text": "用 TON 支付。地址：{addr}",
        "shorts_text": "你好！添加你的 API 密钥即可定期接收优质视频。",
        "add_key": "添加密钥",
        "my_keys": "我的密钥",
        "enter_key": "请一次性发送你的 API 密钥：",
        "key_saved": "已发送密钥，正在检查…",
        "key_ok": "完成！后续由服务处理。",
        "key_failed": "发送失败，请稍后再试。",
        "no_keys": "你还没有密钥（或后端不可用）。",
        "keys_header": "你的密钥：",
        "delete": "删除",
    },
}
